import TodosList from "./TodosList"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <main style={{
    display:"flex"
   }}>
    <div>
      {/* @ts-ignore */}
      <TodosList/>
    </div>
    <div>
      {children}
    </div>
   </main>
  )
}
