// import Search from "./Search"

import Search from "./Search";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main
      style={{
        display: "flex",
      }}
    >
      <div>
        <h1>Search</h1>
      </div>
      <div>
        {/* @ts-ignore */}
        <Search />
        <div>{children}</div>
      </div>
    </main>
  );
}
